name: Check linting and run tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  lint:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install goveralls
        run: GO111MODULE=off go get -u github.com/mattn/goveralls
      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov ./...
      - name: Submit coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
